# Network Mining

## Lab 1: Norms

#### Notebook Author: Mario Prado

The Norms are qualitative measures of an object's size. In this lab you could see examples of how to implement diverse vector norms using python and the numpy library.

In [1]:
import random
random.seed(1)

### Generating random vectors

In [26]:
n = 3 # vector size
µ = 2 # mean
σ = 2 # std deviation

Vector_A = [random.random() for i in range(n)]
Vector_A

[0.7609477375418205, 0.9522444552911937, 0.926506623785866]

In [27]:
Vector_B = [random.randint(-100,100) for i in range(n)]
Vector_B

[6, 42, 64]

In [28]:
Vector_C = [random.gauss(µ,σ) for i in range(n)]
Vector_C

[4.279651340726846, 3.6562695808235763, 1.7235088501902505]

### Generating random matrices

In [3]:
r = 3
c = 3
a = 1
b = 10
µ = 3 # mean
σ = 2 # std deviation

Matrix_A = [[random.random() for i in range(r)] for j in range(c)]
Matrix_A

[[0.48785665652414756, 0.8933170425576351, 0.3898088070211341],
 [0.6074379962852603, 0.767157629147962, 0.6958328667684435],
 [0.26633056045725956, 0.8018263669964836, 0.5911534350013039]]

In [4]:
Matrix_B = [[random.randint(a,b) for i in range(r)] for j in range(c)]
Matrix_B

[[2, 6, 1], [1, 1, 9], [1, 7, 4]]

In [5]:
Matrix_C = [[random.gauss (µ,σ) for i in range(r)] for j in range(c)]
Matrix_C

[[3.942348154683265, 6.156880005001951, 2.3780485834727774],
 [-0.3461794916007821, 2.4131940194412924, 5.354414825197345],
 [2.0535373623088145, 1.2993547928870246, 5.478886659343592]]

### Infinite Norm

In [6]:
def inf_norm(x):
    a_abs = [abs(num) for num in x]
    return max(a_abs)

print(inf_norm(Vector_A))

0.8474337369372327


### Manhattan Norm

In [7]:
def manhattan_norm(x):
    tmp = 0
    for elem in x:
        tmp = tmp + abs(elem)
    return tmp

print(manhattan_norm(Vector_A))

1.745572600026248


### Euclidean Norm

In [8]:
def euclidean_norm(x):
    tmp = 0
    for elem in x:
        tmp = tmp + abs(elem)** 2
    return tmp ** (1.0 / 2)

print(euclidean_norm(Vector_A))

1.1487163954554545


### P-Norm

In [9]:
import math
def pnorm(x, p=2):
    if math.isinf(p):
        x_abs = [abs(elem) for elem in x]
        return max(x_abs)
    else:
        tmp = 0
        for elem in x:
            tmp = tmp + abs(elem)** p
    return tmp ** (1.0 / p)

print(pnorm(Vector_A))

1.1487163954554545


### Dot Product

In [10]:
import math
def inner_prod(X,Y):
    sum = 0
    for i in range(len(X)):
        sum += X[i]*Y[i]
    return sum

print(inner_prod(Vector_A, Vector_B))

-44.16497003614836


#### Dot Product v2

In [11]:
def inner_prodt(X,Y):
    dotproduct = 0
    for i,j in zip(X,Y):
        dotproduct += i*j
    return dotproduct

print(inner_prodt(Vector_A, Vector_B))

-44.16497003614836


### Matrix-Vector Multiplication

In [12]:
def MatVec(A,v): 
    return [inner_prodt(r,v) for r in A ]

print(MatVec(Matrix_A, Vector_A))

[1.1203035635896992, 1.2631926863922587, 1.1667880085733444]


### Matrix-Matrix Multiplication

In [13]:
def matrixmult (A, B): 
    rows_A = len(A); cols_A = len(A[0]); 
    rows_B = len(B); cols_B = len(B[0]) 
    if cols_A != rows_B: 
        print("Cannot multiply the two matrices. Incorrect dimensions.") 
        return 
    C = [[0 for row in range(cols_B)] for col in range(rows_A)] 
    for i in range(rows_A): 
        for j in range(cols_B): 
            for k in range(cols_A): 
                C[i][j] += A[i][k] * B[k][j] 
    return C

print(matrixmult(Matrix_A, Matrix_B))

[[2.2588391626270643, 6.549118630850459, 10.0869452676274], [2.6778664884869263, 9.282615674238627, 10.295188125690693], [1.9256409229123066, 6.537883774749169, 9.847381603430826]]


## Using numpy

In [14]:
import numpy as np 
np.random.seed(1)

### Generating  random vectors

In [29]:
l = 1
h = 100
n = 3

vector_A = np.random.rand(n) # Random vector of size n
vector_A

array([0.69187711, 0.31551563, 0.68650093])

In [30]:
vector_B = np.random.randn(n) # Return samples from the “standard normal” distribution
vector_B

array([-0.85005238,  0.96082   , -0.21741818])

In [31]:
vector_C = np.random.randint(l, h, n) # Random vector of size n with values in [l, h]
vector_C

array([23, 10, 68])

### Generating  random matrices 

In [32]:
l = 1
h = 100
r = 3
c = 3

matrix_A = np.random.rand(r, c) 
matrix_A

array([[0.29361415, 0.28777534, 0.13002857],
       [0.01936696, 0.67883553, 0.21162812],
       [0.26554666, 0.49157316, 0.05336255]])

In [33]:
matrix_B = np.random.randn(r, c) 
matrix_B

array([[ 0.15851488, -1.11731035,  0.2344157 ],
       [ 1.65980218,  0.74204416, -0.19183555],
       [-0.88762896, -0.74715829,  1.6924546 ]])

In [34]:
matrix_C = np.random.randint(l, h, (r,c))
matrix_C

array([[78,  7, 53],
       [86, 71,  3],
       [77, 92, 22]])

### Norms in numpy

In [17]:
# Infinite Norm
L_inf = np.linalg.norm(vector_A, np.inf) 
L_inf

0.7203244934421581

In [18]:
# Manhattan Norm
L_1 = np.linalg.norm(vector_A, 1) 
L_1

1.137460872962077

In [19]:
# Euclidean Norm
L_2 = np.linalg.norm(vector_A, 2) 
L_2

0.8323309085576807

In [20]:
# P-Norm
p = 5
L_p = np.linalg.norm(vector_A, p) 
L_p

0.7294592597385884

In [25]:
Fro_norm = np.linalg.norm(matrix_A, ord='fro') # Frobenius Norm (for matrix)
Fro_norm

1.878249197140613

### Matrix and Vector Operations in numpy

In [20]:
Dotproduct = np.dot(vector_A, vector_B)
Dotproduct

-0.6579878958774171

In [21]:
Matvect = np.dot(matrix_A, vector_A) 
Matvect

array([0.53820436, 0.88126388, 0.85617656])

In [22]:
Matmult = np.dot(matrix_A, matrix_B) 
Matmult

array([[-0.80538256, -0.05871325,  0.58767243],
       [-0.7585049 , -0.59673889,  0.85334412],
       [-0.52344491, -0.88325442,  1.04189144]])

In [23]:
Matmult2 = np.matmul(matrix_A, matrix_B)
Matmult2

array([[-0.80538256, -0.05871325,  0.58767243],
       [-0.7585049 , -0.59673889,  0.85334412],
       [-0.52344491, -0.88325442,  1.04189144]])

## Comparing our code execution time against numpy

#### Matrix Generation

In [24]:
%%timeit -n 1 -r 1

# Our matrix generator
Matrix_D = [[random.random() for i in range(1000)] for j in range(1000)]

456 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)


In [25]:
%%timeit -n 1 -r 1

# Numpy matrix generator
matrix_D = np.random.rand(1000, 1000)

45.8 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)


#### Matrix Product

In [26]:
matrix_D = np.random.rand(100, 100)
matrix_E = np.random.rand(100, 100)

In [27]:
%%timeit -n 1 -r 1

# Our matrix multiplication
matrixmult(matrix_D, matrix_E)

1.93 s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)


In [28]:
%%timeit -n 1 -r 1

# numpy matrix multiplication
np.matmul(matrix_D, matrix_E)

24.7 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)
